### ISSUE TITLE
Trouble with 'import' and using inquirer-test with Mocha

### ISSUE THREAD

**Issue by Christine-horrocks** [ewnd9/inquirer-test#4]
Hello,
This a bit of a two pronged question. The first area I am having trouble with is importing inquirer-test. I keep getting the message: 
SyntaxError: Unexpected token import. 
I have been googling the error and the only answer I can come up with is that import doesn't work with node.js, but if that is the case how did you manage to get it to work for you?

The second sticky point has come as I am trying to convert your AVA examples into a Mocha test and keep coming a cropper at the await function, as it says it is not defined. Is there a way of structuring the syntax so that it might work with await as a key word?

Thank you for your help.

**Comment by ewnd9** [comment]
Hello,

I pushed `mocha` example `test/test-mocha.js` without `import` and `await`.

Please, keep in mind there was a version bump to `v2.0.1` with breaking changes around `inquirer`  (now it uses promises instead of callback) and arguments in `inquirer-test` itself.

However, if you don't want to upgrade, you could copy this file and change only the first arg in `run`: e.g. from `run([cliPath], [ENTER])` to `run(cliPath, [ENTER])`

Hope it helps.

**Comment by Christine-horrocks** [comment]
Hello,

Thank you for your message and the updates! I have passed this onto my team and they are really happy. 

Best wishes,
Christine

**Comment by ewnd9** [comment]
Glad I could help :wave:
